### ISSUE TITLE
Numerical overflow in Thermo.ipynb

### ISSUE THREAD

**Issue by JacobHA** [cwaitt/QWavE#4]
It seems like in examples/Thermo.ipynb, particularly in the cell starting:

# We are going to make up a frequency here that is more intense than what we computed
# to illustrate a point made later

`freq_inplane = 643 # in-plane frequency vibration (degenerate)`
`freq_normal = 249 # out-of-plane frequency vibration`

`Q_HO_in = qwave.q_HO(freq_inplane,temp,'eV')`
`Q_HO_out = qwave.q_HO(freq_normal,temp,'eV')`

that there needs to be a better way of working with overflows.
The Q_HO_in and Q_HO_out are essentially zero b/c of very large negative numbers in the exponential. Works if frequencies are much much less...

**Comment by cwaitt** [comment]
Made significant updates to QWavE. Curently removed this module but will be reintroduced at a later date.
